import './globals.css'
import type { Metadata } from 'next'
import Navbar from '../components/navbar'


export const metadata: Metadata = {
  title: 'LunalED',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className="relative">
        
      <Navbar styleCss="bg-red-500 w-[100px]" textName='LALA'/>
{children}</body>      

    </html>
  )
}
