"use client";

import { NavbarContact } from "@/components";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "LunalED",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative light bg-lightTheme dark:bg-darkTheme dark:text-lightTheme text-darkTheme">
        <NavbarContact />
        {children}
      </body>
    </html>
  );
}
